CREATE DATABASE QLTV
USE QLTV
GO

-- Sao không lưu sách còn lại trong kho còn
CREATE TABLE SACH
(
	MASACH INT IDENTITY PRIMARY KEY NOT NULL,
	TENSACH NVARCHAR(50) NOT NULL,
	MALOAI INT NOT NULL,
	MATG INT NOT NULL,
	SOLUONGTON INT NOT NULL
)
GO

-- Nên thêm "NOTE" column để ghi ý nghĩa của thể loại
CREATE TABLE LOAISACH
(
	MALOAI INT IDENTITY PRIMARY KEY NOT NULL,
	THELOAI NVARCHAR(50) NOT NULL,
	NOTE NVARCHAR(255),
)
GO
	
--- thiếu khóa học của sinh viên
-- them delete flag
CREATE TABLE DOCGIA
(
	MATHE INT IDENTITY PRIMARY KEY NOT NULL,
	HOTENSV NVARCHAR(50) NOT NULL,
	NIENKHOA INT NOT NULL,
	GIOITINH BIT NOT NULL,
	ISDELETED BIT NOT NULL
)
GO

--PHIEU MUON
-- Sao không để ngày mượn trên đây
CREATE TABLE PHIEUMUON
(
	MAPHIEUMUON INT IDENTITY PRIMARY KEY NOT NULL,
	MATHE INT NOT NULL,
	NGAYMUON DATETIME NOT NULL, 
	TONGMUON INT NOT NULL
)
GO

--sau khong lưu tình trạng sách ở đay 
-- Nên thêm "NOTE" column để ghi ý nghĩa của thể loại
CREATE TABLE CT_PHIEUMUON
(
	MASACH INT NOT NULL,  
	MAPHIEUMUON INT NOT NULL, 	
	DEADLINE DATETIME NOT NULL,
	TINHTRANG TINYINT NOT NULL,
	NOTE NVARCHAR(255),
	PRIMARY KEY(MASACH, MAPHIEUMUON,TINHTRANG)
)
GO

--PHIEU TRA
--thiếu MAPHIEUMUON
CREATE TABLE PHIEUTRA
(
	MAPHIEUTRA INT IDENTITY PRIMARY KEY NOT NULL,
	MAPHIEUMUON INT NOT NULL,
	MATHE INT NOT NULL,
	TONGTRA INT NOT NULL,
	NGAYTRA DATETIME NOT NULL,
	HOPLE BIT NOT NULL
)
GO

--sau khong lưu tình trạng sách ở đay 
CREATE TABLE CT_PHIEUTRA
(
	MASACH INT NOT NULL,
	MAPHIEUTRA INT NOT NULL,
	TINHTRANG TINYINT NOT NULL,
	PRIMARY KEY(MASACH, MAPHIEUTRA,TINHTRANG)
)
GO

--BIEN BAN
-- thiếu ngày nhập
-- Nên thêm "NOTE" column để ghi chi tiet hon 
CREATE TABLE BIENBAN
(
	MABIENBAN INT IDENTITY PRIMARY KEY NOT NULL,
	MATHE INT NOT NULL,
	NGAYLAP DATETIME NOT NULL,
	LYDO NVARCHAR(250) NULL,
	HINHTHUC TINYINT NOT NULL,
	NOTE NVARCHAR(255),
)
GO

CREATE TABLE TACGIA
(
	MATG INT IDENTITY PRIMARY KEY NOT NULL,
	TENTG INT NOT NULL,
	NGAYSINH DATETIME NOT NULL,
	GIOITINH BIT NOT NULL,
)
GO

-- thiếu bảng TACGIA
-- Nếu có bảng DOCGIA vậy các bảng lưu tên SV làm gì 



--FK
ALTER TABLE SACH
	ADD CONSTRAINT FK_SACH_LOAISACH
		FOREIGN KEY (MALOAI) REFERENCES LOAISACH(MALOAI);

ALTER TABLE SACH
	ADD CONSTRAINT FK_SACH_TACGIA
		FOREIGN KEY (MATG) REFERENCES TACGIA(MATG);

ALTER TABLE PHIEUMUON
	ADD CONSTRAINT FK_PHIEUMUON_DOCGIA
		FOREIGN KEY (MATHE) REFERENCES DOCGIA(MATHE);

ALTER TABLE CT_PHIEUMUON
	ADD CONSTRAINT FK_CT_PHIEUMUON_PHIEUMUON
		FOREIGN KEY (MAPHIEUMUON) REFERENCES PHIEUMUON(MAPHIEUMUON);

ALTER TABLE CT_PHIEUMUON
	ADD CONSTRAINT FK_CT_PHIEUMUON_SACH
		FOREIGN KEY (MASACH) REFERENCES SACH(MASACH);

ALTER TABLE PHIEUTRA
	ADD CONSTRAINT FK_PHIEUTRA_PHIEUMUON
		FOREIGN KEY (MAPHIEUMUON) REFERENCES PHIEUMUON(MAPHIEUMUON);

ALTER TABLE PHIEUTRA
	ADD CONSTRAINT FK_PHIEUTRA_DOCGIA
		FOREIGN KEY (MATHE) REFERENCES DOCGIA(MATHE);

ALTER TABLE CT_PHIEUTRA
	ADD CONSTRAINT FK_CT_PHIEUTRA_PHIEUTRA
		FOREIGN KEY (MAPHIEUTRA) REFERENCES PHIEUTRA(MAPHIEUTRA);

ALTER TABLE CT_PHIEUTRA
	ADD CONSTRAINT FK_CT_PHIEUTRA_SACH
		FOREIGN KEY (MASACH) REFERENCES SACH(MASACH);


ALTER TABLE BIENBAN
	ADD CONSTRAINT FK_BIENBAN_DOCGIA
		FOREIGN KEY (MATHE) REFERENCES DOCGIA(MATHE);

